//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinavOlusturma.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public System.Guid Id { get; set; }
        public string QuestionContent { get; set; }
        public string OptionA { get; set; }
        public string OptionB { get; set; }
        public string OptionC { get; set; }
        public string OptionD { get; set; }
        public string Answer { get; set; }
        public Nullable<System.Guid> ExamId { get; set; }
    
        public virtual Exam Exam { get; set; }
    }
}
